# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2_test2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.splitter_all = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_all.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_all.setObjectName("splitter_all")
        self.splitter = QtWidgets.QSplitter(self.splitter_all)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.Widget_topLeft = QtWidgets.QWidget(self.splitter)
        self.Widget_topLeft.setObjectName("Widget_topLeft")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.Widget_topLeft)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.Widget_chooseVideo = QtWidgets.QWidget(self.Widget_topLeft)
        self.Widget_chooseVideo.setObjectName("Widget_chooseVideo")
        self.gridLayout = QtWidgets.QGridLayout(self.Widget_chooseVideo)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Label_video = QtWidgets.QLabel(self.Widget_chooseVideo)
        self.Label_video.setObjectName("Label_video")
        self.horizontalLayout_2.addWidget(self.Label_video)
        self.ComboBox_chooseVideo = QtWidgets.QComboBox(self.Widget_chooseVideo)
        self.ComboBox_chooseVideo.setEditable(False)
        self.ComboBox_chooseVideo.setObjectName("ComboBox_chooseVideo")
        self.horizontalLayout_2.addWidget(self.ComboBox_chooseVideo)
        self.PushButton_confirmVideo = QtWidgets.QPushButton(self.Widget_chooseVideo)
        self.PushButton_confirmVideo.setObjectName("PushButton_confirmVideo")
        self.horizontalLayout_2.addWidget(self.PushButton_confirmVideo)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.Widget_chooseVideo, 0, 0, 1, 1)
        self.Frame_vidInfo = QtWidgets.QFrame(self.Widget_topLeft)
        self.Frame_vidInfo.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width: 10")
        self.Frame_vidInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_vidInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_vidInfo.setObjectName("Frame_vidInfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Frame_vidInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Label_vidInfo_title = QtWidgets.QLabel(self.Frame_vidInfo)
        self.Label_vidInfo_title.setObjectName("Label_vidInfo_title")
        self.gridLayout_2.addWidget(self.Label_vidInfo_title, 0, 0, 1, 1)
        self.Label_info_project = QtWidgets.QLabel(self.Frame_vidInfo)
        self.Label_info_project.setStyleSheet("")
        self.Label_info_project.setText("")
        self.Label_info_project.setObjectName("Label_info_project")
        self.gridLayout_2.addWidget(self.Label_info_project, 1, 0, 1, 1)
        self.Label_info_video = QtWidgets.QLabel(self.Frame_vidInfo)
        self.Label_info_video.setStyleSheet("")
        self.Label_info_video.setText("")
        self.Label_info_video.setObjectName("Label_info_video")
        self.gridLayout_2.addWidget(self.Label_info_video, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.Frame_vidInfo, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 1, 1, 1, 1)
        self.Splitter_frames_play = QtWidgets.QSplitter(self.splitter)
        self.Splitter_frames_play.setOrientation(QtCore.Qt.Horizontal)
        self.Splitter_frames_play.setObjectName("Splitter_frames_play")
        self.Widget_frames = QtWidgets.QWidget(self.Splitter_frames_play)
        self.Widget_frames.setObjectName("Widget_frames")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Widget_frames)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 3, 0, 1, 1)
        self.Frame_adjustBB = QtWidgets.QFrame(self.Widget_frames)
        self.Frame_adjustBB.setEnabled(False)
        self.Frame_adjustBB.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_adjustBB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_adjustBB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_adjustBB.setObjectName("Frame_adjustBB")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Frame_adjustBB)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Widget_changeBBSize = QtWidgets.QWidget(self.Frame_adjustBB)
        self.Widget_changeBBSize.setObjectName("Widget_changeBBSize")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Widget_changeBBSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Label_BBSize_desc = QtWidgets.QLabel(self.Widget_changeBBSize)
        self.Label_BBSize_desc.setObjectName("Label_BBSize_desc")
        self.horizontalLayout_6.addWidget(self.Label_BBSize_desc)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.Label_BBSize_x = QtWidgets.QLabel(self.Widget_changeBBSize)
        self.Label_BBSize_x.setObjectName("Label_BBSize_x")
        self.horizontalLayout_6.addWidget(self.Label_BBSize_x)
        self.SpinBox_BBSize_x = QtWidgets.QSpinBox(self.Widget_changeBBSize)
        self.SpinBox_BBSize_x.setMinimum(30)
        self.SpinBox_BBSize_x.setMaximum(200)
        self.SpinBox_BBSize_x.setProperty("value", 100)
        self.SpinBox_BBSize_x.setObjectName("SpinBox_BBSize_x")
        self.horizontalLayout_6.addWidget(self.SpinBox_BBSize_x)
        self.Label_BBSize_y = QtWidgets.QLabel(self.Widget_changeBBSize)
        self.Label_BBSize_y.setObjectName("Label_BBSize_y")
        self.horizontalLayout_6.addWidget(self.Label_BBSize_y)
        self.SpinBox_BBSize_y = QtWidgets.QSpinBox(self.Widget_changeBBSize)
        self.SpinBox_BBSize_y.setMinimum(30)
        self.SpinBox_BBSize_y.setMaximum(200)
        self.SpinBox_BBSize_y.setProperty("value", 100)
        self.SpinBox_BBSize_y.setObjectName("SpinBox_BBSize_y")
        self.horizontalLayout_6.addWidget(self.SpinBox_BBSize_y)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.Widget_changeBBSize, 1, 0, 1, 1)
        self.RadioButton_adjustBB = QtWidgets.QRadioButton(self.Frame_adjustBB)
        self.RadioButton_adjustBB.setObjectName("RadioButton_adjustBB")
        self.gridLayout_3.addWidget(self.RadioButton_adjustBB, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.Frame_adjustBB, 3, 1, 1, 1)
        self.Label_frame = QtWidgets.QLabel(self.Widget_frames)
        self.Label_frame.setEnabled(True)
        self.Label_frame.setObjectName("Label_frame")
        self.gridLayout_11.addWidget(self.Label_frame, 0, 0, 1, 3)
        self.Widget_moveFrames = QtWidgets.QWidget(self.Widget_frames)
        self.Widget_moveFrames.setObjectName("Widget_moveFrames")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Widget_moveFrames)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.PushButton_goLeftLeft = QtWidgets.QPushButton(self.Widget_moveFrames)
        self.PushButton_goLeftLeft.setObjectName("PushButton_goLeftLeft")
        self.horizontalLayout_3.addWidget(self.PushButton_goLeftLeft)
        self.PushButton_goLeft = QtWidgets.QPushButton(self.Widget_moveFrames)
        self.PushButton_goLeft.setObjectName("PushButton_goLeft")
        self.horizontalLayout_3.addWidget(self.PushButton_goLeft)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.PushButton_goRight = QtWidgets.QPushButton(self.Widget_moveFrames)
        self.PushButton_goRight.setObjectName("PushButton_goRight")
        self.horizontalLayout_3.addWidget(self.PushButton_goRight)
        self.PushButton_goRightRight = QtWidgets.QPushButton(self.Widget_moveFrames)
        self.PushButton_goRightRight.setObjectName("PushButton_goRightRight")
        self.horizontalLayout_3.addWidget(self.PushButton_goRightRight)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.Widget_moveFrames, 2, 0, 1, 3)
        self.Label_showFrame = QtWidgets.QLabel(self.Widget_frames)
        self.Label_showFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_showFrame.sizePolicy().hasHeightForWidth())
        self.Label_showFrame.setSizePolicy(sizePolicy)
        self.Label_showFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_showFrame.setText("")
        self.Label_showFrame.setObjectName("Label_showFrame")
        self.gridLayout_11.addWidget(self.Label_showFrame, 1, 0, 1, 3)
        self.Widget_play = QtWidgets.QWidget(self.Splitter_frames_play)
        self.Widget_play.setObjectName("Widget_play")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Widget_play)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.Frame_play = QtWidgets.QFrame(self.Widget_play)
        self.Frame_play.setEnabled(False)
        self.Frame_play.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_play.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_play.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_play.setObjectName("Frame_play")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Frame_play)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Label_nrFrames = QtWidgets.QLabel(self.Frame_play)
        self.Label_nrFrames.setObjectName("Label_nrFrames")
        self.horizontalLayout_7.addWidget(self.Label_nrFrames)
        self.DoubleSpinBox_secPerFrame = QtWidgets.QDoubleSpinBox(self.Frame_play)
        self.DoubleSpinBox_secPerFrame.setMinimum(0.2)
        self.DoubleSpinBox_secPerFrame.setMaximum(5.0)
        self.DoubleSpinBox_secPerFrame.setSingleStep(0.2)
        self.DoubleSpinBox_secPerFrame.setProperty("value", 1.0)
        self.DoubleSpinBox_secPerFrame.setObjectName("DoubleSpinBox_secPerFrame")
        self.horizontalLayout_7.addWidget(self.DoubleSpinBox_secPerFrame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PushButton_play = QtWidgets.QPushButton(self.Frame_play)
        self.PushButton_play.setObjectName("PushButton_play")
        self.horizontalLayout_9.addWidget(self.PushButton_play)
        self.PushButton_pause = QtWidgets.QPushButton(self.Frame_play)
        self.PushButton_pause.setObjectName("PushButton_pause")
        self.horizontalLayout_9.addWidget(self.PushButton_pause)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.Frame_play)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.Splitter_right = QtWidgets.QSplitter(self.splitter_all)
        self.Splitter_right.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_right.setObjectName("Splitter_right")
        self.Widget_method = QtWidgets.QWidget(self.Splitter_right)
        self.Widget_method.setEnabled(False)
        self.Widget_method.setObjectName("Widget_method")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Widget_method)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.Widget_method)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.ComboBox_compute = QtWidgets.QComboBox(self.Widget_method)
        self.ComboBox_compute.setObjectName("ComboBox_compute")
        self.ComboBox_compute.addItem("")
        self.ComboBox_compute.addItem("")
        self.horizontalLayout_10.addWidget(self.ComboBox_compute)
        self.PushButton_compute = QtWidgets.QPushButton(self.Widget_method)
        self.PushButton_compute.setObjectName("PushButton_compute")
        self.horizontalLayout_10.addWidget(self.PushButton_compute)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.Widget_method_parameters = QtWidgets.QWidget(self.Splitter_right)
        self.Widget_method_parameters.setObjectName("Widget_method_parameters")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.Widget_method_parameters)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Frame_nrNN = QtWidgets.QFrame(self.Widget_method_parameters)
        self.Frame_nrNN.setEnabled(False)
        self.Frame_nrNN.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_nrNN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_nrNN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_nrNN.setObjectName("Frame_nrNN")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Frame_nrNN)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Label_nrNN = QtWidgets.QLabel(self.Frame_nrNN)
        self.Label_nrNN.setObjectName("Label_nrNN")
        self.verticalLayout_2.addWidget(self.Label_nrNN)
        self.SpinBox_chooseNumberNN = QtWidgets.QSpinBox(self.Frame_nrNN)
        self.SpinBox_chooseNumberNN.setMinimum(1)
        self.SpinBox_chooseNumberNN.setMaximum(50)
        self.SpinBox_chooseNumberNN.setProperty("value", 12)
        self.SpinBox_chooseNumberNN.setObjectName("SpinBox_chooseNumberNN")
        self.verticalLayout_2.addWidget(self.SpinBox_chooseNumberNN)
        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.Frame_nrNN, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem9, 0, 1, 1, 1)
        self.Frame_embSource = QtWidgets.QFrame(self.Widget_method_parameters)
        self.Frame_embSource.setEnabled(False)
        self.Frame_embSource.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_embSource.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_embSource.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_embSource.setObjectName("Frame_embSource")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Frame_embSource)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Label_embedding = QtWidgets.QLabel(self.Frame_embSource)
        self.Label_embedding.setObjectName("Label_embedding")
        self.verticalLayout_9.addWidget(self.Label_embedding)
        self.RadioButton_embedding = QtWidgets.QRadioButton(self.Frame_embSource)
        self.RadioButton_embedding.setObjectName("RadioButton_embedding")
        self.verticalLayout_9.addWidget(self.RadioButton_embedding)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.Frame_embSource, 0, 2, 1, 1)
        self.Label_showResult_title = QtWidgets.QLabel(self.Splitter_right)
        self.Label_showResult_title.setObjectName("Label_showResult_title")
        self.Label_showResult = QtWidgets.QLabel(self.Splitter_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_showResult.sizePolicy().hasHeightForWidth())
        self.Label_showResult.setSizePolicy(sizePolicy)
        self.Label_showResult.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_showResult.setText("")
        self.Label_showResult.setObjectName("Label_showResult")
        self.widget = QtWidgets.QWidget(self.Splitter_right)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.PushButton_saveResult = QtWidgets.QPushButton(self.widget)
        self.PushButton_saveResult.setEnabled(False)
        self.PushButton_saveResult.setObjectName("PushButton_saveResult")
        self.horizontalLayout.addWidget(self.PushButton_saveResult)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.Widget_Info = QtWidgets.QWidget(self.Splitter_right)
        self.Widget_Info.setObjectName("Widget_Info")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Widget_Info)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(234, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.Label_info_inbetween = QtWidgets.QLabel(self.Widget_Info)
        self.Label_info_inbetween.setText("")
        self.Label_info_inbetween.setObjectName("Label_info_inbetween")
        self.horizontalLayout_4.addWidget(self.Label_info_inbetween)
        spacerItem13 = QtWidgets.QSpacerItem(234, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.gridLayout_13.addWidget(self.splitter_all, 0, 0, 1, 1)
        self.Widget_method.raise_()
        self.PushButton_goRight.raise_()
        self.Widget_method_parameters.raise_()
        self.Widget_Info.raise_()
        self.Widget_frames.raise_()
        self.Widget_play.raise_()
        self.Frame_play.raise_()
        self.Widget_topLeft.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Similarity"))
        self.Label_video.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">1. Choose Video</span></p></body></html>"))
        self.PushButton_confirmVideo.setText(_translate("MainWindow", "Load Video"))
        self.Label_vidInfo_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Video Information</span></p></body></html>"))
        self.Label_BBSize_desc.setText(_translate("MainWindow", "Size:"))
        self.Label_BBSize_x.setText(_translate("MainWindow", "x"))
        self.Label_BBSize_y.setText(_translate("MainWindow", "y"))
        self.RadioButton_adjustBB.setText(_translate("MainWindow", "Adjust Area of Interest"))
        self.Label_frame.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">2. Choose Frame and Area of Interest (ROI)</span></p></body></html>"))
        self.PushButton_goLeftLeft.setText(_translate("MainWindow", "-5"))
        self.PushButton_goLeft.setText(_translate("MainWindow", "-1"))
        self.PushButton_goRight.setText(_translate("MainWindow", "+1"))
        self.PushButton_goRightRight.setText(_translate("MainWindow", "+5"))
        self.Label_nrFrames.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">#Frames per Second</p></body></html>"))
        self.PushButton_play.setText(_translate("MainWindow", "Play"))
        self.PushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">3. Choose Method</span></p></body></html>"))
        self.ComboBox_compute.setItemText(0, _translate("MainWindow", "Nearest Neighbors"))
        self.ComboBox_compute.setItemText(1, _translate("MainWindow", "Low-dim Embedding"))
        self.PushButton_compute.setText(_translate("MainWindow", "Compute"))
        self.Label_nrNN.setText(_translate("MainWindow", "<html><head/><body><p>#Nearest Neighbors</p></body></html>"))
        self.Label_embedding.setText(_translate("MainWindow", "Embedding"))
        self.RadioButton_embedding.setText(_translate("MainWindow", "Show only Current Video"))
        self.Label_showResult_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Result</p></body></html>"))
        self.PushButton_saveResult.setText(_translate("MainWindow", "Save"))

