# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2_test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1376, 897)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Splitter_right = QtWidgets.QSplitter(self.centralwidget)
        self.Splitter_right.setGeometry(QtCore.QRect(760, 0, 581, 871))
        self.Splitter_right.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_right.setObjectName("Splitter_right")
        self.Splitter_method_result = QtWidgets.QSplitter(self.Splitter_right)
        self.Splitter_method_result.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_method_result.setObjectName("Splitter_method_result")
        self.Splitter_method = QtWidgets.QSplitter(self.Splitter_method_result)
        self.Splitter_method.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_method.setObjectName("Splitter_method")
        self.Widget_method = QtWidgets.QWidget(self.Splitter_method)
        self.Widget_method.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Widget_method.sizePolicy().hasHeightForWidth())
        self.Widget_method.setSizePolicy(sizePolicy)
        self.Widget_method.setObjectName("Widget_method")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Widget_method)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.Widget_method)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.ComboBox_compute_2 = QtWidgets.QComboBox(self.Widget_method)
        self.ComboBox_compute_2.setObjectName("ComboBox_compute_2")
        self.ComboBox_compute_2.addItem("")
        self.ComboBox_compute_2.addItem("")
        self.horizontalLayout_11.addWidget(self.ComboBox_compute_2)
        self.PushButton_compute_2 = QtWidgets.QPushButton(self.Widget_method)
        self.PushButton_compute_2.setObjectName("PushButton_compute_2")
        self.horizontalLayout_11.addWidget(self.PushButton_compute_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.Splitter_method)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(52)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Frame_nrNN_2 = QtWidgets.QFrame(self.layoutWidget_3)
        self.Frame_nrNN_2.setEnabled(False)
        self.Frame_nrNN_2.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_nrNN_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_nrNN_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_nrNN_2.setObjectName("Frame_nrNN_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Frame_nrNN_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Label_nrNN = QtWidgets.QLabel(self.Frame_nrNN_2)
        self.Label_nrNN.setObjectName("Label_nrNN")
        self.verticalLayout_5.addWidget(self.Label_nrNN)
        self.SpinBox_chooseNumberNN_2 = QtWidgets.QSpinBox(self.Frame_nrNN_2)
        self.SpinBox_chooseNumberNN_2.setMinimum(1)
        self.SpinBox_chooseNumberNN_2.setMaximum(50)
        self.SpinBox_chooseNumberNN_2.setProperty("value", 12)
        self.SpinBox_chooseNumberNN_2.setObjectName("SpinBox_chooseNumberNN_2")
        self.verticalLayout_5.addWidget(self.SpinBox_chooseNumberNN_2)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.Frame_nrNN_2)
        self.Frame_embSource_2 = QtWidgets.QFrame(self.layoutWidget_3)
        self.Frame_embSource_2.setEnabled(False)
        self.Frame_embSource_2.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_embSource_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_embSource_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_embSource_2.setObjectName("Frame_embSource_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Frame_embSource_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.Frame_embSource_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.RadioButton_embedding_2 = QtWidgets.QRadioButton(self.Frame_embSource_2)
        self.RadioButton_embedding_2.setObjectName("RadioButton_embedding_2")
        self.verticalLayout_11.addWidget(self.RadioButton_embedding_2)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.Frame_embSource_2)
        self.Splitter_result = QtWidgets.QSplitter(self.Splitter_method_result)
        self.Splitter_result.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_result.setObjectName("Splitter_result")
        self.Label_showResult_title = QtWidgets.QLabel(self.Splitter_result)
        self.Label_showResult_title.setObjectName("Label_showResult_title")
        self.Label_showResult = QtWidgets.QLabel(self.Splitter_result)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_showResult.sizePolicy().hasHeightForWidth())
        self.Label_showResult.setSizePolicy(sizePolicy)
        self.Label_showResult.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_showResult.setText("")
        self.Label_showResult.setObjectName("Label_showResult")
        self.layoutWidget_4 = QtWidgets.QWidget(self.Splitter_result)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.PushButton_saveResult_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.PushButton_saveResult_2.setEnabled(False)
        self.PushButton_saveResult_2.setObjectName("PushButton_saveResult_2")
        self.horizontalLayout_8.addWidget(self.PushButton_saveResult_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.Splitter_info = QtWidgets.QSplitter(self.Splitter_right)
        self.Splitter_info.setOrientation(QtCore.Qt.Horizontal)
        self.Splitter_info.setObjectName("Splitter_info")
        self.Label_info_inbetween = QtWidgets.QLabel(self.Splitter_info)
        self.Label_info_inbetween.setText("")
        self.Label_info_inbetween.setObjectName("Label_info_inbetween")
        self.Splitter_mid = QtWidgets.QSplitter(self.centralwidget)
        self.Splitter_mid.setGeometry(QtCore.QRect(480, 0, 245, 816))
        self.Splitter_mid.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_mid.setObjectName("Splitter_mid")
        self.Frame_play = QtWidgets.QFrame(self.Splitter_mid)
        self.Frame_play.setEnabled(False)
        self.Frame_play.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_play.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_play.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_play.setObjectName("Frame_play")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Frame_play)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PushButton_play = QtWidgets.QPushButton(self.Frame_play)
        self.PushButton_play.setObjectName("PushButton_play")
        self.horizontalLayout_9.addWidget(self.PushButton_play)
        self.PushButton_pause = QtWidgets.QPushButton(self.Frame_play)
        self.PushButton_pause.setObjectName("PushButton_pause")
        self.horizontalLayout_9.addWidget(self.PushButton_pause)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Label_slider = QtWidgets.QLabel(self.Frame_play)
        self.Label_slider.setObjectName("Label_slider")
        self.horizontalLayout_7.addWidget(self.Label_slider)
        self.DoubleSpinBox_secPerFrame = QtWidgets.QDoubleSpinBox(self.Frame_play)
        self.DoubleSpinBox_secPerFrame.setMinimum(0.2)
        self.DoubleSpinBox_secPerFrame.setMaximum(5.0)
        self.DoubleSpinBox_secPerFrame.setSingleStep(0.2)
        self.DoubleSpinBox_secPerFrame.setProperty("value", 1.0)
        self.DoubleSpinBox_secPerFrame.setObjectName("DoubleSpinBox_secPerFrame")
        self.horizontalLayout_7.addWidget(self.DoubleSpinBox_secPerFrame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.Splitter_left = QtWidgets.QSplitter(self.centralwidget)
        self.Splitter_left.setGeometry(QtCore.QRect(0, 0, 571, 871))
        self.Splitter_left.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_left.setObjectName("Splitter_left")
        self.Widget_chooseVideo = QtWidgets.QWidget(self.Splitter_left)
        self.Widget_chooseVideo.setObjectName("Widget_chooseVideo")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Widget_chooseVideo)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 451, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Label_video = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Label_video.setObjectName("Label_video")
        self.horizontalLayout_2.addWidget(self.Label_video)
        self.ComboBox_chooseVideo = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.ComboBox_chooseVideo.setEditable(False)
        self.ComboBox_chooseVideo.setObjectName("ComboBox_chooseVideo")
        self.horizontalLayout_2.addWidget(self.ComboBox_chooseVideo)
        self.PushButton_confirmVideo = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.PushButton_confirmVideo.setObjectName("PushButton_confirmVideo")
        self.horizontalLayout_2.addWidget(self.PushButton_confirmVideo)
        self.Frame_videoInfo = QtWidgets.QFrame(self.Splitter_left)
        self.Frame_videoInfo.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-width: 10")
        self.Frame_videoInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_videoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_videoInfo.setObjectName("Frame_videoInfo")
        self.Label_info_project = QtWidgets.QLabel(self.Frame_videoInfo)
        self.Label_info_project.setGeometry(QtCore.QRect(10, 40, 231, 31))
        self.Label_info_project.setStyleSheet("")
        self.Label_info_project.setText("")
        self.Label_info_project.setObjectName("Label_info_project")
        self.Label_info_video = QtWidgets.QLabel(self.Frame_videoInfo)
        self.Label_info_video.setGeometry(QtCore.QRect(10, 70, 489, 41))
        self.Label_info_video.setStyleSheet("")
        self.Label_info_video.setText("")
        self.Label_info_video.setObjectName("Label_info_video")
        self.Label_videoInfo = QtWidgets.QLabel(self.Frame_videoInfo)
        self.Label_videoInfo.setGeometry(QtCore.QRect(10, 10, 171, 18))
        self.Label_videoInfo.setObjectName("Label_videoInfo")
        self.splitter_choseFrame_spacer = QtWidgets.QSplitter(self.Splitter_left)
        self.splitter_choseFrame_spacer.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_choseFrame_spacer.setObjectName("splitter_choseFrame_spacer")
        self.Splitter_chooseFrame = QtWidgets.QSplitter(self.splitter_choseFrame_spacer)
        self.Splitter_chooseFrame.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_chooseFrame.setObjectName("Splitter_chooseFrame")
        self.Label_frame = QtWidgets.QLabel(self.Splitter_chooseFrame)
        self.Label_frame.setEnabled(True)
        self.Label_frame.setObjectName("Label_frame")
        self.Label_showFrame = QtWidgets.QLabel(self.Splitter_chooseFrame)
        self.Label_showFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_showFrame.sizePolicy().hasHeightForWidth())
        self.Label_showFrame.setSizePolicy(sizePolicy)
        self.Label_showFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Label_showFrame.setText("")
        self.Label_showFrame.setObjectName("Label_showFrame")
        self.Widget_moveFrames = QtWidgets.QWidget(self.Splitter_chooseFrame)
        self.Widget_moveFrames.setEnabled(False)
        self.Widget_moveFrames.setObjectName("Widget_moveFrames")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Widget_moveFrames)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 409, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.PushButton_goLeftLeft = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PushButton_goLeftLeft.setEnabled(False)
        self.PushButton_goLeftLeft.setObjectName("PushButton_goLeftLeft")
        self.horizontalLayout_3.addWidget(self.PushButton_goLeftLeft)
        self.PushButton_goLeft = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PushButton_goLeft.setEnabled(False)
        self.PushButton_goLeft.setObjectName("PushButton_goLeft")
        self.horizontalLayout_3.addWidget(self.PushButton_goLeft)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.PushButton_goRight = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PushButton_goRight.setEnabled(False)
        self.PushButton_goRight.setObjectName("PushButton_goRight")
        self.horizontalLayout_3.addWidget(self.PushButton_goRight)
        self.PushButton_goRightRight = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PushButton_goRightRight.setEnabled(False)
        self.PushButton_goRightRight.setObjectName("PushButton_goRightRight")
        self.horizontalLayout_3.addWidget(self.PushButton_goRightRight)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.Splitter_adjustBB = QtWidgets.QSplitter(self.Splitter_chooseFrame)
        self.Splitter_adjustBB.setOrientation(QtCore.Qt.Horizontal)
        self.Splitter_adjustBB.setObjectName("Splitter_adjustBB")
        self.Frame_adjustBB = QtWidgets.QFrame(self.Splitter_adjustBB)
        self.Frame_adjustBB.setEnabled(False)
        self.Frame_adjustBB.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.Frame_adjustBB.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_adjustBB.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_adjustBB.setObjectName("Frame_adjustBB")
        self.Widget_changeBBSize = QtWidgets.QWidget(self.Frame_adjustBB)
        self.Widget_changeBBSize.setGeometry(QtCore.QRect(30, 30, 251, 60))
        self.Widget_changeBBSize.setObjectName("Widget_changeBBSize")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Widget_changeBBSize)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 231, 39))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Label_BBSize_desc = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Label_BBSize_desc.setObjectName("Label_BBSize_desc")
        self.horizontalLayout_6.addWidget(self.Label_BBSize_desc)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.Label_BBSize_x = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Label_BBSize_x.setObjectName("Label_BBSize_x")
        self.horizontalLayout_6.addWidget(self.Label_BBSize_x)
        self.SpinBox_BBSize_x = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.SpinBox_BBSize_x.setMinimum(30)
        self.SpinBox_BBSize_x.setMaximum(200)
        self.SpinBox_BBSize_x.setProperty("value", 100)
        self.SpinBox_BBSize_x.setObjectName("SpinBox_BBSize_x")
        self.horizontalLayout_6.addWidget(self.SpinBox_BBSize_x)
        self.Label_BBSize_y = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.Label_BBSize_y.setObjectName("Label_BBSize_y")
        self.horizontalLayout_6.addWidget(self.Label_BBSize_y)
        self.SpinBox_BBSize_y = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.SpinBox_BBSize_y.setMinimum(30)
        self.SpinBox_BBSize_y.setMaximum(200)
        self.SpinBox_BBSize_y.setProperty("value", 100)
        self.SpinBox_BBSize_y.setObjectName("SpinBox_BBSize_y")
        self.horizontalLayout_6.addWidget(self.SpinBox_BBSize_y)
        self.horizontalLayoutWidget_3.raise_()
        self.RadioButton_adjustBB = QtWidgets.QRadioButton(self.Frame_adjustBB)
        self.RadioButton_adjustBB.setGeometry(QtCore.QRect(60, 10, 191, 23))
        self.RadioButton_adjustBB.setObjectName("RadioButton_adjustBB")
        self.Widget_changeBBSize.raise_()
        self.RadioButton_adjustBB.raise_()
        self.Label_info_inbetween.raise_()
        self.Frame_adjustBB.raise_()
        self.Frame_play.raise_()
        self.Frame_videoInfo.raise_()
        self.Widget_method.raise_()
        self.RadioButton_adjustBB.raise_()
        self.RadioButton_adjustBB.raise_()
        self.Widget_chooseVideo.raise_()
        self.Widget_method.raise_()
        self.layoutWidget_3.raise_()
        self.Widget_moveFrames.raise_()
        self.Label_showFrame.raise_()
        self.Label_frame.raise_()
        self.layoutWidget_4.raise_()
        self.Label_showResult_title.raise_()
        self.Label_showResult.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Similarity"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">3. Choose Method</span></p></body></html>"))
        self.ComboBox_compute_2.setItemText(0, _translate("MainWindow", "Nearest Neighbors"))
        self.ComboBox_compute_2.setItemText(1, _translate("MainWindow", "Low-dim Embedding"))
        self.PushButton_compute_2.setText(_translate("MainWindow", "Compute"))
        self.Label_nrNN.setText(_translate("MainWindow", "<html><head/><body><p>#Nearest Neighbors</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Embedding"))
        self.RadioButton_embedding_2.setText(_translate("MainWindow", "Show only Current Video"))
        self.Label_showResult_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Result</p></body></html>"))
        self.PushButton_saveResult_2.setText(_translate("MainWindow", "Save"))
        self.PushButton_play.setText(_translate("MainWindow", "Play"))
        self.PushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.Label_slider.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">#Frames per Second</p></body></html>"))
        self.Label_video.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">1. Choose Video</span></p></body></html>"))
        self.PushButton_confirmVideo.setText(_translate("MainWindow", "Load Video"))
        self.Label_videoInfo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Video Information</span></p></body></html>"))
        self.Label_frame.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">2. Choose Frame and Area of Interest (ROI)</span></p></body></html>"))
        self.PushButton_goLeftLeft.setText(_translate("MainWindow", "-5"))
        self.PushButton_goLeft.setText(_translate("MainWindow", "-1"))
        self.PushButton_goRight.setText(_translate("MainWindow", "+1"))
        self.PushButton_goRightRight.setText(_translate("MainWindow", "+5"))
        self.Label_BBSize_desc.setText(_translate("MainWindow", "Size:"))
        self.Label_BBSize_x.setText(_translate("MainWindow", "x"))
        self.Label_BBSize_y.setText(_translate("MainWindow", "y"))
        self.RadioButton_adjustBB.setText(_translate("MainWindow", "Adjust Area of Interest"))

